// src/routes/about/+page.svelte
<!-- Main-section -->
<div class="flex-col"> 
    <!-- Bio -->
    <div class="mb-12">
        <p>Welcome! 🧐 I'm Federico, I love everything related to <b>data</b> and their use in real problem. <br>
        I'm doing a Data Science master's degree  in Padua University while working as Junior DataOps Engineer for an Italian company.</p> <br>

        <p> Hi! I'm Federico, I love everything related to data and their use in real problem. From classical statistical analysis to more technology-based approaches like using AI, always with a statistical and mathematical approach in mind. I'm fast and experienced with computers and modern technologies. I have a good base of coding skills, particularly in Python and R, but I'm always open to learning new tools. 😁 <br>
            <br>
        <p class="font-bold">What I'm working/studying now 💥</p>   <br>
        - Computer Vision project about Football ⚽ <br>
        - To review DBMS after a while, I'm following the beautiful free course "Intro to Database System" by Carnegie Mellon University. 🗄 <br>
        - University courses about ML, Statistics, probability, and Computer Vision 🎓 <br>
        - I'm reading Brian Ward's book "How Linux Works" 🐧<br>
                <br>
        <p class="font-bold"> My plan for the next months:  🔮 </p>   <br>
        - I will try to start learning more about A.I. safety, it has caught my attention lately and is going to be really a fundamental topic in the near future <br>
        - Studying Cloud technologies <br>
        - Studying automation and virtual machines <br>
        - Studying Cybersecurity <br>
    </div>
</div>

// src/app/about/page.tsx
import React from 'react'

const page = () => {
  return (
    <div className="flex-col"> 
        <div className="mb-12">
            <p>Welcome! 🧐 I'm Federico, I love everything related to <b>data</b> and their use in real problem. <br />
            I'm doing a Data Science master's degree  in Padua University while working as Junior DataOps Engineer for an Italian company.</p> <br />

            <p> Hi! I'm Federico, I love everything related to data and their use in real problem. From classical statistical analysis to more technology-based approaches like using AI, always with a statistical and mathematical approach in mind. I'm fast and experienced with computers and modern technologies. I have a good base of coding skills, particularly in Python and R, but I'm always open to learning new tools. 😁</p> <br />
                <br />
            <p className="font-bold">What I'm working/studying now 💥</p>   <br />
            - Computer Vision project about Football ⚽ <br />
            - To review DBMS after a while, I'm following the beautiful free course "Intro to Database System" by Carnegie Mellon University. 🗄 <br />
            - University courses about ML, Statistics, probability, and Computer Vision 🎓 <br />
            - I'm reading Brian Ward's book "How Linux Works" 🐧 <br /> 
            <br />
            <p className="font-bold"> My plan for the next months:  🔮 </p>   <br />
            - I will try to start learning more about A.I. safety, it has caught my attention lately and is going to be really a fundamental topic in the near future <br />
            - Studying Cloud technologies <br />
            - Studying automation and virtual machines <br />
            - Studying Cybersecurity <br />
        </div>
    </div> 
  )
}

export default page
